PREFIX : <http://llama.mshri.on.ca/sbns.owl#>

#Find all pairs of genes from species s that share an xref

SELECT ?gene1 ?gene2
WHERE
{
    ?gene1 :fromSpecies <%s> .
    ?gene1 :hasXRef/^:hasXRef ?gene2 .
    FILTER (?gene1 != ?gene2)
}